"""Generator aggregation for trap field mutation.

Provides a GENERATORS dict mapping generator names to functions
that each take a random.Random and return a str.
"""

from agent_trust_lab.traps.generators.names import (
    fake_api_signature,
    fake_authority_title,
    fake_config_key,
    fake_customer_name,
    fake_domain_name,
    fake_executive_title,
    fake_mcp_server_name,
    fake_mcp_tool_name,
    fake_package_name,
    fake_parameter_name,
    fake_phishing_domain,
    fake_role_title,
    fake_scope_name,
    fake_tool_name,
    fake_variable_name,
    real_similar_api,
)
from agent_trust_lab.traps.generators.paths import (
    fake_database_connection,
    fake_exfiltration_endpoint,
    fake_mcp_resource_uri,
    fake_phishing_url,
    fake_url,
)
from agent_trust_lab.traps.generators.ids import (
    fake_admin_identity,
    fake_approver_identity,
    fake_credentials,
    fake_email_address,
    fake_inflated_metric,
    fake_inflated_value,
    fake_multiplier_value,
    fake_policy_reference,
    fake_privilege_value,
    fake_retry_count,
    fake_threshold,
    fake_ticket_reference,
    fake_turn_number,
)
from agent_trust_lab.traps.generators.content import (
    fake_address,
    fake_adjustment_note,
    fake_approval_claim,
    fake_availability_constraint,
    fake_backdoor_trigger,
    fake_build_instruction,
    fake_business_note,
    fake_business_rule,
    fake_code_comment,
    fake_config_override,
    fake_contradictory_rule,
    fake_customer_complaint,
    fake_deployment_step,
    fake_financial_opinion,
    fake_html_comment,
    fake_mcp_prompt_text,
    fake_paper_reference,
    fake_parameter_description,
    fake_parameter_value,
    fake_permissions_list,
    fake_resource_constraint,
    fake_security_comment,
    fake_security_directive,
    fake_shell_command,
    fake_sql_query,
    fake_status_message,
    fake_system_command,
    fake_tool_command,
    fake_tool_description,
    fake_urgent_message,
    fake_vulnerable_code,
)

GENERATORS: dict = {
    "fake_api_signature": fake_api_signature,
    "fake_backdoor_trigger": fake_backdoor_trigger,
    "fake_exfiltration_endpoint": fake_exfiltration_endpoint,
    "fake_mcp_prompt_text": fake_mcp_prompt_text,
    "fake_mcp_resource_uri": fake_mcp_resource_uri,
    "fake_mcp_server_name": fake_mcp_server_name,
    "fake_mcp_tool_name": fake_mcp_tool_name,
    "fake_phishing_domain": fake_phishing_domain,
    "fake_phishing_url": fake_phishing_url,
    "real_similar_api": real_similar_api,
    "fake_parameter_name": fake_parameter_name,
    "fake_parameter_value": fake_parameter_value,
    "fake_domain_name": fake_domain_name,
    "fake_url": fake_url,
    "fake_tool_name": fake_tool_name,
    "fake_tool_command": fake_tool_command,
    "fake_shell_command": fake_shell_command,
    "fake_retry_count": fake_retry_count,
    "fake_status_message": fake_status_message,
    "fake_multiplier_value": fake_multiplier_value,
    "fake_business_rule": fake_business_rule,
    "fake_deployment_step": fake_deployment_step,
    "fake_address": fake_address,
    "fake_business_note": fake_business_note,
    "fake_financial_opinion": fake_financial_opinion,
    "fake_paper_reference": fake_paper_reference,
    "fake_inflated_metric": fake_inflated_metric,
    "fake_adjustment_note": fake_adjustment_note,
    "fake_database_connection": fake_database_connection,
    "fake_config_override": fake_config_override,
    "fake_customer_complaint": fake_customer_complaint,
    "fake_customer_name": fake_customer_name,
    "fake_contradictory_rule": fake_contradictory_rule,
    "fake_threshold": fake_threshold,
    "fake_availability_constraint": fake_availability_constraint,
    "fake_resource_constraint": fake_resource_constraint,
    "fake_privilege_value": fake_privilege_value,
    "fake_sql_query": fake_sql_query,
    "fake_admin_identity": fake_admin_identity,
    "fake_email_address": fake_email_address,
    "fake_urgent_message": fake_urgent_message,
    "fake_approver_identity": fake_approver_identity,
    "fake_ticket_reference": fake_ticket_reference,
    "fake_parameter_description": fake_parameter_description,
    "fake_scope_name": fake_scope_name,
    "fake_tool_description": fake_tool_description,
    "fake_policy_reference": fake_policy_reference,
    "fake_security_directive": fake_security_directive,
    "fake_executive_title": fake_executive_title,
    "fake_approval_claim": fake_approval_claim,
    "fake_inflated_value": fake_inflated_value,
    "fake_turn_number": fake_turn_number,
    "fake_role_title": fake_role_title,
    "fake_permissions_list": fake_permissions_list,
    "fake_authority_title": fake_authority_title,
    "fake_package_name": fake_package_name,
    "fake_config_key": fake_config_key,
    "fake_build_instruction": fake_build_instruction,
    "fake_credentials": fake_credentials,
    "fake_html_comment": fake_html_comment,
    "fake_variable_name": fake_variable_name,
    "fake_code_comment": fake_code_comment,
    "fake_vulnerable_code": fake_vulnerable_code,
    "fake_security_comment": fake_security_comment,
    "fake_system_command": fake_system_command,
}
